
export const recipeData = [
    {
        img: "https://source.unsplash.com/random/100",
        food: "Sopapilla Dessert",
        cal: "1044.8",
        carbs: "30.4",
        protein: "3.2",
        fat: "102.8",
        fiber: "1",
    },
    {
        img: "https://source.unsplash.com/random/200",
        food: "Frozen Yogurt Blueberries",
        cal: "35",
        carbs: "7",
        protein: "1.2",
        fat: "0.8",
        fiber: "0.5",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/100",
        food: "Sopapilla Dessert",
        cal: "1044.8",
        carbs: "30.4",
        protein: "3.2",
        fat: "102.8",
        fiber: "1",
    },
    {
        img: "https://source.unsplash.com/random/200",
        food: "Frozen Yogurt Blueberries",
        cal: "35",
        carbs: "7",
        protein: "1.2",
        fat: "0.8",
        fiber: "0.5",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/100",
        food: "Sopapilla Dessert",
        cal: "1044.8",
        carbs: "30.4",
        protein: "3.2",
        fat: "102.8",
        fiber: "1",
    },
    {
        img: "https://source.unsplash.com/random/200",
        food: "Frozen Yogurt Blueberries",
        cal: "35",
        carbs: "7",
        protein: "1.2",
        fat: "0.8",
        fiber: "0.5",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/100",
        food: "Sopapilla Dessert",
        cal: "1044.8",
        carbs: "30.4",
        protein: "3.2",
        fat: "102.8",
        fiber: "1",
    },
    {
        img: "https://source.unsplash.com/random/200",
        food: "Frozen Yogurt Blueberries",
        cal: "35",
        carbs: "7",
        protein: "1.2",
        fat: "0.8",
        fiber: "0.5",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/100",
        food: "Sopapilla Dessert",
        cal: "1044.8",
        carbs: "30.4",
        protein: "3.2",
        fat: "102.8",
        fiber: "1",
    },
    {
        img: "https://source.unsplash.com/random/200",
        food: "Frozen Yogurt Blueberries",
        cal: "35",
        carbs: "7",
        protein: "1.2",
        fat: "0.8",
        fiber: "0.5",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/100",
        food: "Sopapilla Dessert",
        cal: "1044.8",
        carbs: "30.4",
        protein: "3.2",
        fat: "102.8",
        fiber: "1",
    },
    {
        img: "https://source.unsplash.com/random/200",
        food: "Frozen Yogurt Blueberries",
        cal: "35",
        carbs: "7",
        protein: "1.2",
        fat: "0.8",
        fiber: "0.5",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
    {
        img: "https://source.unsplash.com/random/300",
        food: "Seared Scallops With Pan Sauce",
        cal: "251.5",
        carbs: "7.2",
        protein: "30.2",
        fat: "12.1",
        fiber: "0.1",
    },
];

